# Generated by Django 2.2.5 on 2019-09-29 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpiceGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('color', models.CharField(max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hexadecimal color code', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('image', models.FilePathField(null=True, path='/home/abiery/Projects/spicy/spicegallery/assets/spicegallery/images')),
                ('basic_description', models.TextField(default='Scientific name.')),
                ('extended_description', models.TextField(default='History, flavor, and uses of this spice.')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SpiceMix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('color', models.CharField(max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hexadecimal color code', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('origin', models.CharField(default='This spice mix has multiple origins.', max_length=30)),
                ('dishes', models.TextField(default='Dishes which the spice mix complements.')),
                ('spices', models.ManyToManyField(to='spicegallery.SpiceGallery')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
